kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: airline-predictions-stream
  namespace: builds-tutorial
  labels:
    app: airline-predictions-stream
    app.kubernetes.io/component: airline-predictions-stream
    app.kubernetes.io/instance: airline-predictions-stream
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'airline-predictions-stream:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    # option to replace Dockerfile FROM image with ImageStreamTag image
    #dockerStrategy:
    #  dockerfilePath: foo/bar
    #  from:
    #    kind: ImageStreamTag
    #    name: 'python:latest'
    #    namespace: openshift
    # option to replace Dockerfile FROM image with another specified image
    #dockerStrategy:
    #  from:
    #    kind: DockerImage
    #    name: openjdk:8-jre
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/ably77/airlineprediction-stream'
  triggers:
    - type: GitHub
      github:
        secret: H5yQIfcBCx8VngIGRFWF
    - type: Generic
      generic:
        secret: diHWHFwkdgFnKARLPuc3
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: airline-predictions-stream
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  namespace: builds-tutorial
  labels:
    app: airline-predictions-stream
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - airline-predictions-stream
        from:
          kind: ImageStreamTag
          namespace: builds-tutorial
          name: 'airline-predictions-stream:latest'
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: airline-predictions-stream
    deploymentconfig: airline-predictions-stream
  template:
    metadata:
      labels:
        app: airline-predictions-stream
        deploymentconfig: airline-predictions-stream
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: airline-predictions-stream
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  name: airline-predictions-stream
  namespace: builds-tutorial
  labels:
    app: airline-predictions-stream
    app.kubernetes.io/component: airline-predictions-stream
    app.kubernetes.io/instance: airline-predictions-stream
spec:
  lookupPolicy:
    local: false